name: Cypress Tests (Localhost)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./Cypress_Automation/cypress-demo

      # 4️⃣ Start local server in background
      - name: Start local server
        run: npm start &
        working-directory: ./Cypress_Automation/cypress-demo

      # 5️⃣ Wait for server to be ready (port 3000)
      - name: Wait for server
        run: npx wait-on --timeout 60000 http://localhost:3000
        working-directory: ./Cypress_Automation/cypress-demo

      - name: Debug homepage HTML
        run: curl -s http://localhost:3000 | head -n 20
        working-directory: ./Cypress_Automation/cypress-demo


      # 6️⃣ Run Cypress tests (using local server)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Cypress_Automation/cypress-demo
          browser: chrome
          headed: false
